---
- name: "Show Instance Environment"
  shell: |
    env
    cd /home/ubuntu/
    mkdir udapeople_app

  #Extract from achieved
# - name: "Extract the achieved artifact "
#   unarchive:
#     src: ./artifact.tar.gz
#     dest: /home/ubuntu/udapeople_app

# - name: "Copy backend compiled code"
#   become: yes
#   synchronize:
#     src: ../../backend/dist
#     dest: /home/ubuntu/udapeople_app
#     recursive: true

# - name: "copy node_functions"
#   become: yes
#   synchronize:
#     src: ../../backend/node_modules
#     dest: /home/ubuntu/udapeople_app
#     recursive: true

# Get bucket name 
- name:               Get Radar exe url
  shell:              curl https://kvdb.io/VMYQi71XYivasRDqmX9fy9/s3name
  register:           shell_output

#Download the backend artifact from s3

- name: "Show Instance Environment"
  shell: |
    echo {{ shell_output.stdout }}
    aws s3 cp s3://{{ shell_output.stdout }}/artifact.tar.gz /home/ubuntu/udapeople_app/artifact.tar.gz

#Extract from achieved
- name: "Extract the achieved artifact "
  unarchive:
    src: /home/ubuntu/udapeople_app/artifact.tar.gz
    dest: /home/ubuntu/udapeople_app    

# - name: Download object from AWS S3 bucket using Ansible
#   hosts: localhost
#   tasks:
#   - name: GET/DOWNLOAD file from S3 bucket
#     amazon.aws.aws_s3:
#       profile: personal
#       bucket: udapeople-${CIRCLE_WORKFLOW_ID:0:7}
#       mode: get
#       object: "artifact.tar.gz"
#       dest: "/home/ubuntu/udapeople_app"
#     register: getresult
#   - debug: 
#       msg="{{ getresult.msg }}" 
#     when: getresult.changed



- name: "delete running programmes"
  become: true
  command: |
    pm2 delete all
  ignore_errors: true

- name: "Start App"
  become: true
  command: |
    pm2 start -f ./main.js
  args:
    chdir: /home/ubuntu/udapeople_app/dist

  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"
    TYPEORM_ENTITIES: "./modules/domain/**/*.entity"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
    TYPEORM_MIGRATIONS: "./migrations/*.js"
    TYPEORM_MIGRATIONS_DIR: "./migrations"
