---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "Remove dependences that are no longer required"
  become: yes
  apt:
    autoremove: yes

# - name: enable pyenv and install python
#   shell: /home/ubuntu/.pyenv/bin/pyenv init - && /home/www/.pyenv/bin/pyenv install 3.4.3 chdir=/home/ubuntu
#   environment:
#     pyenv_root: /home/ubuntu/.pyenv
#     path: "{{ pyenv_root }}/bin:$PATH"
#   become: yes
#   become_user: ubuntu

- name: "install dependencies"
  become: yes
  apt:
    name:
      - nodejs
      - npm
      
    state: latest
    update_cache: yes
  
- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present